package registerlogin;

import java.io.IOException;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Karalee
 */
public class CoinRequest extends javax.swing.JFrame {

	int coinAmount;//# coins being requested
	String username;//username of person requesting
	String userToRequestCoins;//our username
    /**
     * Creates new form CoinRequest
     */
    public CoinRequest() {
        initComponents();
        setSize(630, 400);
        setLocation(300,20);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    public void setParameters(int coinAmount_, String username_, String userToRequestCoins_)
    {
    	coinAmount = coinAmount_;
        username = username_;
        userToRequestCoins = userToRequestCoins_;
        setMessage();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">    
    private void setMessage()
    {
    	jLabel1.setText(username+" has requested "+coinAmount+" coins");
    }
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        acceptBtn = new javax.swing.JButton();
        RejectBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Username has requested n coins");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(145, 72, 410, 58);

        acceptBtn.setBackground(new java.awt.Color(179, 11, 11));
        acceptBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        acceptBtn.setText("Accept");
        acceptBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBtnActionPerformed(evt);
            }
        });
        getContentPane().add(acceptBtn);
        acceptBtn.setBounds(380, 196, 121, 52);

        RejectBtn.setBackground(new java.awt.Color(179, 11, 11));
        RejectBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        RejectBtn.setText("Reject");
        RejectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RejectBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RejectBtn);
        RejectBtn.setBounds(150, 196, 121, 52);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerlogin/gradient-white-yellow-linear-1920x1080-c2-ffffff-ffd700-a-90-f-14.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 680, 400);

        pack();
    }// </editor-fold>                        

    public void close(){
        this.setVisible(false);
        this.dispose();
    }
    private void RejectBtnActionPerformed(java.awt.event.ActionEvent evt) {                                   
        // reject coin request
    	Message mToSend = new Message(3,userToRequestCoins);//make reject message
    	mToSend.userToRequestCoins = username;//this is user that requested's username
    	try
		{
        	StartUp.startUp.oos.writeObject(mToSend);
        	StartUp.startUp.oos.flush(); 
        	close();
		}
		catch(IOException ioe)
		{
			System.out.println("ioe: "+ioe.getMessage());
			close();
		}
    }                                         

    private void acceptBtnActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // accept coin request
    	if(StartUp.user.getCoin() < coinAmount)//do not have enough coins to give, so poopup saying not enough
    	{
    		JFrame parent = new JFrame();
            JOptionPane.showMessageDialog(parent, "You do not have enough coins!");
    	}
    	else//has enough coins to give
    	{
    		Message mToSend = new Message(2,userToRequestCoins);//make reject message
        	mToSend.userToRequestCoins = username;//this is user that requested's username
        	try
    		{
            	StartUp.startUp.oos.writeObject(mToSend);
            	StartUp.startUp.oos.flush();
            	//success
            	StartUp.user.setCoin(StartUp.user.getCoin() - coinAmount);
            	close();
    		}
    		catch(IOException ioe)
    		{
    			System.out.println("ioe: "+ioe.getMessage());
    			close();
    		}
    	}
    }                                         

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoinRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoinRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoinRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoinRequest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoinRequest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton RejectBtn;
    private javax.swing.JButton acceptBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration                   
}

