/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registerlogin;

import com.mygdx.game.desktop.DesktopLauncher;

/**
 *
 * @author Karalee
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setSize(1296,1005);
        setLocation(300,20);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    public void close(){
        this.setVisible(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        multiplayerBtn = new javax.swing.JButton();
        singlePlayerBtn = new javax.swing.JButton();
        friendsBtn = new javax.swing.JButton();
        storeBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        scoresBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        multiplayerBtn.setBackground(new java.awt.Color(179, 11, 11));
        multiplayerBtn.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        multiplayerBtn.setForeground(new java.awt.Color(250, 250, 250));
        multiplayerBtn.setText("Multiplayer");
        multiplayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                multiplayerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(multiplayerBtn);
        multiplayerBtn.setBounds(465, 500, 367, 80);

        singlePlayerBtn.setBackground(new java.awt.Color(179, 11, 11));
        singlePlayerBtn.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        singlePlayerBtn.setForeground(new java.awt.Color(250, 250, 250));
        singlePlayerBtn.setText("Single Player");
        singlePlayerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                singlePlayerBtnActionPerformed(evt);
            }
        });
        getContentPane().add(singlePlayerBtn);
        singlePlayerBtn.setBounds(465, 348, 367, 80);

        friendsBtn.setBackground(new java.awt.Color(179, 11, 11));
        friendsBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        friendsBtn.setForeground(new java.awt.Color(250, 250, 250));
        friendsBtn.setText("Friends");
        friendsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                friendsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(friendsBtn);
        friendsBtn.setBounds(30, 870, 145, 57);

        storeBtn.setBackground(new java.awt.Color(179, 11, 11));
        storeBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        storeBtn.setForeground(new java.awt.Color(250, 250, 250));
        storeBtn.setText("Store");
        storeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        storeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                storeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(storeBtn);
        storeBtn.setBounds(1122, 40, 145, 57);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel1.setText("Username:");
        jLabel1.setText("Username: "+StartUp.user.getUname());
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 44, 440, 26);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel2.setText("High Score:");
        jLabel2.setText("High Score: "+Integer.toString(StartUp.user.getHighScore()));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 77, 440, 26);

        scoresBtn.setBackground(new java.awt.Color(179, 11, 11));
        scoresBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        scoresBtn.setForeground(new java.awt.Color(250, 250, 250));
        scoresBtn.setText("Scores");
        scoresBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoresBtnActionPerformed(evt);
            }
        });
        getContentPane().add(scoresBtn);
        scoresBtn.setBounds(1110, 870, 145, 57);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerlogin/gradient-white-yellow-linear-1920x1080-c2-ffffff-ffd700-a-90-f-14.png")));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1300, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void multiplayerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_multiplayerBtnActionPerformed
        // go to multiplayer screen
        MultiplayerScreen multiplayer = new MultiplayerScreen();
        close();
    }//GEN-LAST:event_multiplayerBtnActionPerformed

    private void singlePlayerBtnActionPerformed(java.awt.event.ActionEvent evt) {
    	// go to single player game
    	DesktopLauncher gameLauncher = new DesktopLauncher();//make new game launcher
    	boolean x = gameLauncher.run();
    	if(x) {close();}
    }

    private void storeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_storeBtnActionPerformed
        // change screen to store
        Store storeObj = new Store();
        close();
    }//GEN-LAST:event_storeBtnActionPerformed

    private void scoresBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoresBtnActionPerformed
        // show scores screen
        ScoresScreen scores = new ScoresScreen();
        close();
    }//GEN-LAST:event_scoresBtnActionPerformed

    private void friendsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_friendsBtnActionPerformed
        // go to friends frame
        FriendsScreen friends = new FriendsScreen();
        close();
    }//GEN-LAST:event_friendsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton friendsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton multiplayerBtn;
    private javax.swing.JButton scoresBtn;
    private javax.swing.JButton singlePlayerBtn;
    private javax.swing.JButton storeBtn;
    // End of variables declaration//GEN-END:variables
}
