/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registerlogin;

import java.io.IOException;
import java.util.ArrayList;

/**
 *
 * @author Karalee
 */
public class MultiplayerScreen extends javax.swing.JFrame {
    int coinAmount; //amount of coins to request
    /**
     * Creates new form MultiplayerScreen
     */
    public MultiplayerScreen() {
        initComponents();
        setSize(1296,1005);
        setLocation(300,20);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        friendsTable.setEnabled(false);//disable user from editing table text
        coinsNeeded.setEnabled(false);
        coinAmount = 0;
        
      //friends table stuff below
        friendsTable.setEnabled(false);//disable user from editing table text
        friendsTable.getColumnModel().getColumn(0).setPreferredWidth(250);
        friendsTable.getColumnModel().getColumn(1).setPreferredWidth(50);
        friendsTable.setRowHeight(40);
        friendsTable.getTableHeader().setBackground(new java.awt.Color(179, 11, 11));
        friendsTable.getTableHeader().setForeground(new java.awt.Color(250, 250, 250));
        friendsTable.setBackground(new java.awt.Color(250, 250, 250));
        addFriendsToTable();
    }
    
    public void close(){
        this.setVisible(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        coinsNeeded = new javax.swing.JTextField();
        amountLabel = new javax.swing.JLabel();
        increaseAmount = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        friendsTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel1.setText("Coin Request");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(515, 56, 290, 57);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("Username: ");
        jLabel2.setText("Username: "+StartUp.user.getUname());
        getContentPane().add(jLabel2);
        jLabel2.setBounds(36, 56, 430, 27);

        backBtn.setBackground(new java.awt.Color(179, 11, 11));
        backBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(250, 250, 250));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(50, 870, 145, 57);

        coinsNeeded.setFont(new java.awt.Font("Tahoma", 0, 26)); // NOI18N
        coinsNeeded.setText("0");
        getContentPane().add(coinsNeeded);
        coinsNeeded.setBounds(500, 280, 330, 80);

        amountLabel.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        amountLabel.setText("Amount:");
        getContentPane().add(amountLabel);
        amountLabel.setBounds(410, 290, 90, 60);

        increaseAmount.setBackground(new java.awt.Color(179, 11, 11));
        increaseAmount.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        increaseAmount.setForeground(new java.awt.Color(250, 250, 250));
        increaseAmount.setText(">");
        increaseAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                increaseAmountActionPerformed(evt);
            }
        });
        getContentPane().add(increaseAmount);
        increaseAmount.setBounds(760, 220, 70, 60);

        jButton1.setBackground(new java.awt.Color(179, 11, 11));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(250, 250, 250));
        jButton1.setText("<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(500, 220, 70, 60);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("How many coins would you like to request?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(490, 170, 350, 50);

        friendsTable.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        friendsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Username", ""
            }
        ));
        friendsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                friendsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(friendsTable);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(320, 390, 670, 440);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Select friend to request coins from");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 850, 310, 22);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerlogin/gradient-white-yellow-linear-1920x1080-c2-ffffff-ffd700-a-90-f-14.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 1300, 1010);

        pack();
    }// </editor-fold>                        

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // go back home
        Home homeScreen = new Home();
        close();
    }                                       
     private void addFriendsToTable()
    {
        ArrayList <User> friendsList = StartUp.user.getFriends();
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel)friendsTable.getModel();
        model.setRowCount(0);//clear table thing for new friends to be added if refeshed
        for(int i = 0; i < friendsList.size(); i++)
        {
            try
            {
                model.addRow(new Object[]{friendsList.get(i).getUname(), "Request"});
            }
            catch(NullPointerException e)
            {
                System.out.println("MODEL IS NULL???");
            }
        }
        
    }
     private void updateCoinAmountShown()
     {
         coinsNeeded.setText(Integer.toString(coinAmount));
     }
    private void friendsTableMouseClicked(java.awt.event.MouseEvent evt) {                                          
        // if 'unfriend' cell is clicked, unfriend the user
        int row = friendsTable.rowAtPoint(evt.getPoint());
        int col = friendsTable.columnAtPoint(evt.getPoint());
        //update search result table
        System.out.println("ROW CLICKED: "+row);

        String userToRequest = (String)(friendsTable.getModel().getValueAt(row, 0));
        System.out.println("user to request coins from: "+ userToRequest);
        //do thread stuff here, send a message from this serverthread to another server thread
        Message mToSend = new Message(1, StartUp.user.getUname());
        mToSend.coinAmount = coinAmount;
        mToSend.userToRequestCoins = userToRequest;
        try
		{
        	StartUp.startUp.oos.writeObject(mToSend);
        	StartUp.startUp.oos.flush(); 
		}
		catch(IOException ioe)
		{
			System.out.println("ioe: "+ioe.getMessage());
		}

        addFriendsToTable();//update friends table to take the user off friends list
    }                                         

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        //decrease coins to be asked for CANNOT GO NEGATIVE
        if(coinAmount == 0)
        {
            //do nothing
        }
        else
        {
            coinAmount-=5;
        }
        updateCoinAmountShown();
    }                                        

    private void increaseAmountActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        if(coinAmount == 100000)//cannot request more than this
        {
            //do nothing
        }
        else
        {
            coinAmount+=5;
        }
        updateCoinAmountShown();
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiplayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiplayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiplayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiplayerScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MultiplayerScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel amountLabel;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField coinsNeeded;
    private javax.swing.JTable friendsTable;
    private javax.swing.JButton increaseAmount;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                   
}
