/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registerlogin;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setSize(1296,1005);
        setLocation(300,20);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    public void close(){
        this.setVisible(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fnameField = new javax.swing.JTextField();
        lnameField = new javax.swing.JTextField();
        unameField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        passwordField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        picField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        comboSecurity1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        answerField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        answerField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        comboSecurity2 = new javax.swing.JComboBox<>();
        btnRegister = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        fnameField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(fnameField);
        fnameField.setBounds(293, 123, 820, 37);

        lnameField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lnameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lnameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(lnameField);
        lnameField.setBounds(293, 178, 820, 37);

        unameField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(unameField);
        unameField.setBounds(293, 233, 820, 37);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("First Name :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(112, 123, 115, 37);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Last Name :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(112, 178, 115, 37);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Username :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(112, 233, 115, 37);

        emailField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        emailField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailFieldActionPerformed(evt);
            }
        });
        getContentPane().add(emailField);
        emailField.setBounds(293, 290, 820, 37);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Email :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(112, 288, 85, 37);

        passwordField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(passwordField);
        passwordField.setBounds(293, 347, 820, 37);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Password :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(112, 345, 126, 37);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Picture URL : ");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(112, 436, 141, 37);

        picField.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        picField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picFieldActionPerformed(evt);
            }
        });
        getContentPane().add(picField);
        picField.setBounds(293, 436, 820, 37);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel7.setText("Two O' Run");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(533, 36, 185, 47);

        comboSecurity1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "What is your mother's maiden name?", "What is your first pet's name?", "Which city did you born?", "Which city did you grow up?", "What is you favorite sports team?", "What is your high school name?" }));
        getContentPane().add(comboSecurity1);
        comboSecurity1.setBounds(293, 535, 820, 41);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Security Question 1 :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(112, 542, 166, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Answer:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(112, 594, 84, 37);

        answerField1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(answerField1);
        answerField1.setBounds(293, 596, 820, 37);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Security Question 2 :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(112, 688, 174, 37);

        answerField2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        getContentPane().add(answerField2);
        answerField2.setBounds(293, 746, 820, 37);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Answer :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(118, 744, 130, 37);

        comboSecurity2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "  ", "What is your mother's maiden name?", "What is your first pet's name?", "Which city did you born?", "Which city did you grow up?", "What is you favorite sports team?", "What is your high school name?" }));
        getContentPane().add(comboSecurity2);
        comboSecurity2.setBounds(293, 690, 820, 37);

        btnRegister.setBackground(new java.awt.Color(179, 11, 11));
        btnRegister.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnRegister.setForeground(new java.awt.Color(250, 250, 250));
        btnRegister.setText("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegister);
        btnRegister.setBounds(533, 837, 270, 70);

        btnHome.setBackground(new java.awt.Color(179, 11, 11));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(250, 250, 250));
        btnHome.setText("Back");
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        getContentPane().add(btnHome);
        btnHome.setBounds(31, 28, 165, 55);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerlogin/gradient-white-yellow-linear-1920x1080-c2-ffffff-ffd700-a-90-f-14.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 1300, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void picFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_picFieldActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
    	System.out.println(this.getClass().getCanonicalName());
    	// Get values from GUI
        String fname = this.fnameField.getText();
        String lname = this.lnameField.getText();
        String uname = this.unameField.getText();
        String email = this.emailField.getText();
        String pass = this.passwordField.getText();
        String pic = this.picField.getText();
        String sq1 = this.comboSecurity1.getSelectedItem().toString();
        String sa1 = this.answerField1.getText();
        String sq2 = this.comboSecurity2.getSelectedItem().toString();
        String sa2 = this.answerField2.getText();
        //check if username is already being used or not
        User temp = StartUp.userDriver.findByUname(uname);
        User temp2 = StartUp.userDriver.findByEmail(email);
        if(temp != null)//user exists already, error
        {
            JFrame parent1 = new JFrame();
            JOptionPane.showMessageDialog(parent1, "Username already in use. Choose different one.");
        }
        else if(temp2 != null)
        {
            JFrame parent1 = new JFrame();
            JOptionPane.showMessageDialog(parent1, "Email already in use. Choose different one.");
        }
        else
        {
            if(fname.isEmpty()){
                JFrame parent1 = new JFrame();
                JOptionPane.showMessageDialog(parent1, "First name cannot be empty");
            }
            else if(lname.isEmpty()){
                JFrame parent1 = new JFrame();
                JOptionPane.showMessageDialog(parent1, "Last name cannot be empty");
            }
            else if(uname.isEmpty()){
                JFrame parent1 = new JFrame();
                JOptionPane.showMessageDialog(parent1, "Username cannot be empty");
            }
            else if(email.isEmpty()){
                JFrame parent1 = new JFrame();
                JOptionPane.showMessageDialog(parent1, "Email cannot be empty");
            }
            else if(pass.isEmpty()){
                JFrame parent1 = new JFrame();
                JOptionPane.showMessageDialog(parent1, "Password cannot be empty");
            }
            else{
                // Create a user
                StartUp.user = new User(fname, lname, uname, email, sq1, sq2, sa1, sa2, pass, pic);
                System.out.println("User object created");
                // Register user
                StartUp.user.register();
                System.out.print(StartUp.user.getUserID());
                System.out.println("User registered to database");
                JFrame parent = new JFrame();
                JOptionPane.showMessageDialog(parent, "Success!!");
                Home homeScreen = new Home();
                close();
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void lnameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lnameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lnameFieldActionPerformed

    private void emailFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailFieldActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // go back to start screen
        StartScreen start = new StartScreen();
        close();
    }//GEN-LAST:event_btnHomeActionPerformed

    /**
     * @param args tayhe command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField answerField1;
    private javax.swing.JTextField answerField2;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> comboSecurity1;
    private javax.swing.JComboBox<String> comboSecurity2;
    private javax.swing.JTextField emailField;
    private javax.swing.JTextField fnameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lnameField;
    private javax.swing.JTextField passwordField;
    private javax.swing.JTextField picField;
    private javax.swing.JTextField unameField;
    // End of variables declaration//GEN-END:variables
}
