/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package registerlogin;

import com.mygdx.game.MyGame;
import java.awt.Desktop;
import com.mygdx.game.desktop.DesktopLauncher;

/**
 *
 * @author Karalee
 */
//global user variable that will be used throughout the game
public class StartScreen extends javax.swing.JFrame {

    /**
     * Creates new form StartScreen
     */
    public StartScreen() {
        initComponents();
        setSize(1296,1005);
        setLocation(300,20);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    public void close(){
        this.setVisible(false);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        loginBtn = new javax.swing.JButton();
        playAsGuestBtn = new javax.swing.JButton();
        createAccountBtn1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel1.setText("Two O' Run");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(500, 80, 260, 61);

        loginBtn.setBackground(new java.awt.Color(179, 11, 11));
        loginBtn.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        loginBtn.setForeground(new java.awt.Color(250, 250, 250));
        loginBtn.setText("Login");
        loginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginBtn);
        loginBtn.setBounds(436, 273, 402, 87);

        playAsGuestBtn.setBackground(new java.awt.Color(179, 11, 11));
        playAsGuestBtn.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        playAsGuestBtn.setForeground(new java.awt.Color(250, 250, 250));
        playAsGuestBtn.setText("Play As Guest");
        playAsGuestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playAsGuestBtnActionPerformed(evt);
            }
        });
        getContentPane().add(playAsGuestBtn);
        playAsGuestBtn.setBounds(436, 608, 407, 87);

        createAccountBtn1.setBackground(new java.awt.Color(179, 11, 11));
        createAccountBtn1.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        createAccountBtn1.setForeground(new java.awt.Color(250, 250, 250));
        createAccountBtn1.setText("Create Account");
        createAccountBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccountBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(createAccountBtn1);
        createAccountBtn1.setBounds(436, 436, 402, 87);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/registerlogin/gradient-white-yellow-linear-1920x1080-c2-ffffff-ffd700-a-90-f-14.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1300, 1010);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBtnActionPerformed
        // go to login page
        Login loginScreen = new Login();
        close();
    }//GEN-LAST:event_loginBtnActionPerformed

    private void playAsGuestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playAsGuestBtnActionPerformed
        // change screen to the game, no home screen will be accessable
    	StartUp.isGuest = true;
    	System.out.println("Playing as guest: "+StartUp.isGuest);
    	boolean x = DesktopLauncher.run();
    	if(x) {close();}
    	
    }//GEN-LAST:event_playAsGuestBtnActionPerformed

    private void createAccountBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccountBtn1ActionPerformed
        // go to create account page
        Register registerScreen = new Register();
        close();
    }//GEN-LAST:event_createAccountBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createAccountBtn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginBtn;
    private javax.swing.JButton playAsGuestBtn;
    // End of variables declaration//GEN-END:variables
}
